### ISSUE TITLE
Another Install Issue

### ISSUE THREAD

**Issue by MarquisT** [Organice/django-organice#13]
djangocms_picture.Picture.picture: (fields.E300) Field defines a relation with model 'Image', which is either not installed, or is abstract.
djangocms_picture.Picture.thumbnail_options: (fields.E300) Field defines a relation with model 'ThumbnailOption', which is either not installed, or is abstract.

**Comment by bittner** [comment]
Same as in #12. Please try to use one of the documented sets of requirements ("Dependencies" from the [change log](http://docs.organice.io/en/latest/changelog.html)).

A note on development
--------------------
The listed package versions are aged due to the development of django Organice being stalled at the moment. Unfortunately, the dynamic setup doesn't produce reliable results due to the unstable nature of the components chosen. A new release is planned, but with a slightly different approach (continuous delivery, cookiecutter, django SHOP maybe), and more towards the end of this or Spring next year. Zinnia will most probably also have to be phased out from the solution stack.
