### ISSUE TITLE
organice-setup, version conflict issue : installs Django1.5.12 but requires Django>=1.6

### ISSUE THREAD

**Issue by newnovis** [Organice/django-organice#7]
First, please know that I tried to post this issue on the StackOverflow but the tag django-organice is not working. So I used the tags proposed by default*.

I have installed Django-organice (version 0.2) as described in the installation docs (http://docs.organice.io/en/latest/installation.html). All packages were installed but when I execute it `$ organice-setup myexample`
it gives the following error message 
```
Traceback (most recent call last):
File "/pathtomyvirtualenvs/bin/organice-setup", line 5, in <module>
    from pkg_resources import load_entry_point
File "/pathtomyvirtualenvs/local/lib/python2.7/site-packages/pkg_resources.py", line 2720, in <module>
    parse_requirements(_requires_), Environment()
File "/pathtomyvirtualenvs/local/lib/python2.7/site-packages/pkg_resources.py", line 592, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (Django 1.5.12 (/pathtomyvirtualenvs/lib/python2.7/site-packages), Requirement.parse('Django>=1.6'))
```

Thank you for your help (I am a newbie, please let me know if additional log information is needed)

*http://stackoverflow.com/questions/32047547/organice-setup-version-conflict-issue-installs-django1-5-12-but-requires-djan

**Comment by bittner** [comment]
It's fine that you post your issue here. Looks like folks on StackOverflow don't want a new tag.  :anguished:  Let's stick with `django` for now. You did a great job.

According to your error message there something must have gone wrong with your installation steps. Have you installed Django prior to installing `django-organice`? According to [setup.py](https://github.com/Organice/django-organice/blob/develop/setup.py#L35) Django 1.5.8 should be installed.

You would need to provide more information to help figure out which requirement is complaining. Can you post what's the output of your `pip freeze`, and `python --version`?

**Comment by newnovis** [comment]
Please find below the requested information :
`pip freeze` outputs :
`BeautifulSoup==3.2.1
Django==1.5.12
Pillow==2.9.0
South==1.0.2
argparse==1.2.1
beatifulsoup4==4.4.0
cmsplugin-contact==1.1.0
cmsplugin-zinnia=0.5.1
django-allauth=0.23.0
django-analytical==0.22.0
django-apptemplates==0.0.1
django-blog-zinnia==0.13
django-classy-tags==0.6.2
django-cms==2.4.3-support
django-media-tree==0.8.1
django-mptt==0.5.2
django-organice==0.2
django-organice-theme==0.2
django-reversion==1.8.0
django-sekizai==0.8.2
django-simple-links==0.1.1
django-tagging==0.4
django-tinymce==2.0.4
django-todo==1.4
django-xmlrpc==0.1.5
easy-thumbnails==2.2
emencia.django.newsletter==0.3dev
html2text==2015.6.21
html5lib==0.999999
oauthlib==1.0.3
psycopg2==2.6.1
pyparsing==2.0.3
python-dateutil==1.5
python-openid==2.2.5
pytz==2015.4
requests==2.7.0
requests-oauthlib==0.5.0
six==1.9.0
solid-i18n==1.1.0
vobject==0.6.6
wsgiref==0.1.2
xlrd==0.9.4
xlwt==1.0.0`
`python --version?` outputs `Python 2.7.6`
I have added the full traceback to the above post. I hope that the need for the StackOverflow tag will be demonstrated by the django Organice users.  
Thank you

**Comment by bittner** [comment]
Thanks for your support! (... of being a django Organice user)  :smiley: 

What operating system are you using?

**Hint:** You can make the verbose output more readable using the triple-backtick markup ``` (then a newline, then all your code or verbose output, then again the triple-backtick in a single line).

The unfortunate thing is that the output above (in your question) doesn't help us in finding the package that requires Django 1.6+. (The `# XXX` comment, if this is from the source code, tells us that someone already wanted to make the error message more helpful. Obviously, this did not happen. :worried:)

**Note:** If you're not in a hurry, I'm working on upgrading django Organice to Django 1.8.x and django CMS 3.x. This could be working in a week or so.

If you are in a hurry, however, you could to to `"/pathtomyvirtualenvs/local/lib/python2.7/site-packages/pkg_resources.py", line 2720` and add some debug output there to find out which package is complaining.

**Comment by newnovis** [comment]
I am happy to be among the 270/month downloads! I want to use your solution that's why I asked questions :+1: 
I use Ubuntu server 14.04
Thank you for the hint, I updated the above posts.
Could you please provide me with the pip freeze output of an installed django Organice v0.2 in your system? I will compare it with the one installed in my system and feed you back.
In your project roadmap, there is askbot integration in your solution. Will it happen in the upgrade to Django 1.8? 
Thank you

**Comment by bittner** [comment]
@newnovis 
> Could you please provide me with the pip freeze output of an installed django Organice v0.2

Awesome, that's the right question to ask! -- All releases are documented in the [CHANGELOG](http://docs.organice.io/en/latest/changelog.html); see the **Packages** link for a documented snapshot of package versions.

If the issue is just about a clean installation all you need to do is
``` bash
$ pip install -r docs/requirements.txt
```
I should have thought about this earlier, sorry about that.

**Comment by bittner** [comment]
@newnovis Re your question on the roadmap: At the moment Askbot integration is not priority one. Not of v0.3 at least. I'll do the upgrade to the latest Django und django CMS versions first.

Then, probably for v0.4, I plan to add [Foundation](http://foundation.zurb.com/) support, because [Bootstrap](http://getbootstrap.com/) alone is just too rigid as a choice, it doesn't give you enough liberty as a designer. I hope I can manage to support both at the same time with a single [mother theme](https://github.com/Organice/django-organice-theme). That'll be interesting weeks to come... :fearful: 

Afterwards I'm open to add integrations. I must admit, as much as I like Askbot I'm not sure yet how to integrate it from a usability point of view. As of today, django Organice is still just mainly a preconfigured website project (with a few add-ons). The - maybe internal - collaboration workflows and UIs are yet to define, plan and implement. There's nothing out there in the Django ecosystem that can serve as an example yet.  :neutral_face: 

As every serious open source project, of course, I'm open to pull requests, though!  :smiley:

**Comment by newnovis** [comment]
Thank you Sir, your advices solved this issue.
I will continue using your solution and I hope it will work for my project! I will let you know :)

**Comment by bittner** [comment]
Cool! Glad it worked out. I've answered the [question on StackOverflow](http://stackoverflow.com/questions/32047547/organice-setup-version-conflict-issue-installs-django-1-5-12-but-requires-djan?answertab=votes#tab-top), too.
If you could accept the answer there that would be awesome. Cheers!
