### ISSUE TITLE
"OSError: [WinError 193] %1 is not a valid Win32 application" when calling organice-setup

### ISSUE THREAD

**Issue by mkane848** [Organice/django-organice#9]
Following the documentation and calling "organice-setup example", I get:

```
(env) U:\organice\intranet>organice-setup example
Generating project example ...
Traceback (most recent call last):
  File "U:\organice\env\Scripts\organice-setup-script.py", line 9, in <module>
    load_entry_point('django-organice==0.3.dev1', 'console_scripts', 'organice-setup')()
  File "u:\organice\env\lib\site-packages\organice\bin\organice_setup.py", line 577, in startproject
    _create_project()
  File "u:\organice\env\lib\site-packages\organice\bin\organice_setup.py", line 123, in _create_project
    code = call(['django-admin.py', 'startproject', projectname, '.'])
  File "c:\users\mkane\appdata\local\programs\python\python35-32\Lib\subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\mkane\appdata\local\programs\python\python35-32\Lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "c:\users\mkane\appdata\local\programs\python\python35-32\Lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
```

I'm on Windows 10 and using Python 3.5

**Comment by bittner** [comment]
Looks like this is an issue specific to Windows:

* http://stackoverflow.com/questions/25651990/oserror-winerror-193-1-is-not-a-valid-win32-application
* If you're practical with changing source code of the project please change [line 123 in organice_setup.py](https://github.com/Organice/django-organice/blob/master/organice/bin/organice_setup.py#L123) to:
```
code = call(['python', 'django-admin.py', 'startproject', projectname, '.'])
```
If you're just testing and you don't care about reusability edit your `u:\organice\env\lib\site-packages\organice\bin\organice_setup.py` directly.

The python executable must be in your `PATH`. See the [StackOverflow question](http://stackoverflow.com/questions/25651990/oserror-winerror-193-1-is-not-a-valid-win32-application) for solutions otherwise.

On Unix this works because the `django-admin.py` script is made executable using file permissions.

**Comment by mkane848** [comment]
Alright, made the change to organice_setup and I'm now getting a different error.
```
Generating project example ...
python: can't open file 'django-admin.py': [Errno 2] No such file or directory
```

django-admin.py is in fact located in my env\Scripts\ folder

**Comment by bittner** [comment]
Can you try setting the path instead, i.e. restore the `call` code as before (no `python` call) and try as suggested in [StackOverflow question 17836416](http://stackoverflow.com/questions/17836416/add-django-admin-py-path-to-command-line-on-windows-7)? This looks like the appropriate approach.

**Comment by mkane848** [comment]
My path is set at `C:\Users\mkane\AppData\Local\Programs\Python\Python35-32\Scripts`. I've gotten DjangoCMS to run on this environment, if that helps at all

**Comment by bittner** [comment]
Alright, so django CMS' scripts are at the same location as django Organice' scripts? (Which django CMS commands do you execute that work?) If not, try to understand what's the difference. The problem must be there.

Let me know about your findings, so I can incorporate either some changes to the code or provide hints for Windows users in the documentation. Thank you!

**Comment by bittner** [comment]
@mkane848 Mike, if there is anything that you can share what solved your problem please let us know.

**Comment by mkane848** [comment]
I actually didn't get around to solving the problem, just ended up going back to regular DjangoCMS. I'll keep messing with Organice to see if I can figure it out still

**Comment by mkane848** [comment]
I believe the issue is with Windows. Even with the path set, I still have to copy the path to where my django-admin.py file is. So I believe the best tip to put in documentation for Windows users is that if your Path is properly set on Windows but it still can't find django-admin.py, go to line 123 in organice_setup.py and change it to:
```
 code = call(['python', r"<path to virtualenv folder>\Scripts\django-admin.py", 'startproject', projectname, '.'])
```

Which allows the setup script to run properly to completion.

**Comment by bittner** [comment]
Thank you, @mkane848, for this helpful feedback!

I still think we should try to *solve* the problem. Editing the source code is not a solution. Our situation is especially odd, you'd have to go into the sources installed in your virtualenv's `site-packages`, not nice.

If the `PATH` environment variable is set correctly, but `django-admin.py` is not found then something must be wrong with the environment. I suspect the `call` function call results in a new environment which points to the wrong python binary, because the `PATH` environment variable is not set correctly.

I've done a lucky 30-seconds googling (with duckduckgo) and found a hint on [assoc and ftype](http://stackoverflow.com/questions/8012956/python-django-virtualenv-windows#13038526). That could or could not be a helpful puzzle piece. (Actually, this could be used to solve the very first complaint on the command line, where the Windows `cmd` interpreter complains that the `.py` file is "not a valid Win32 application".)

Can you try printing the contents of the `PATH` variable with the `call` function? That should make it clear if I'm suspecting the right culprit.

**Comment by bittner** [comment]
@mkane848 can you try?
```
    code = call(['django-admin', 'startproject', projectname, '.'])
```
This works on Linux, and will most probably work on your Windows system too. I'll change that in the current development version.

**Comment by mkane848** [comment]
Confirming that it works on Windows. Nice catch with the .exe/.py switch!

**Comment by bittner** [comment]
Thank you for reporting the issue and your trouble shooting!
